server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Lzh.102033
    driver-class-name: com.mysql.cj.jdbc.Driver
